[features]
seeds = false
skip-lint = false
[programs.localnet]
token_locker = "ArffnQbDrBUG4zADP9trjUTrsjmmt5n4WFzSrS9gEo5N"
[programs.devnet]
token_locker = "ArffnQbDrBUG4zADP9trjUTrsjmmt5n4WFzSrS9gEo5N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/primary/keydev/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"