[features]
seeds = false
skip-lint = false
[programs.localnet]
token_locker = "CT9n2yqLm8yn4BwZZWvAy4zT9i45gig2dpYiCoUZTKXj"
[programs.devnet]
token_locker = "CT9n2yqLm8yn4BwZZWvAy4zT9i45gig2dpYiCoUZTKXj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/primary/keydev/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"