[features]
seeds = false
skip-lint = false
[programs.localnet]
token_locker = "7M9PoX5GMSTrR5AeiugKD3Kzrt51vLoqNzvJYiS8wdZm"
[programs.devnet]
token_locker = "7M9PoX5GMSTrR5AeiugKD3Kzrt51vLoqNzvJYiS8wdZm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/primary/keydev/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"